
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from PIL import Image, ImageTk
import webbrowser

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\hknge\PycharmProjects\Udemy\CustomTkinter\gerilim_2\build\assets\frame0")
def hesapla(l, p, u, s):
    k = 56  # Sabit
    e = (200 * l * p*1000) / (k * s * u**2) if u == 220 else (100 * l * p*1000) / (k * s * u**2)
    return e

# Sonuçları kontrol etme işlevi
def sonuclari_kontrol_et():
    s1 = float(s_1.get())
    l1 = float(l_1.get())
    u1 = float(u_1.get())
    p1 = float(p_1.get())

    s2 = float(s_2.get())
    l2 = float(l_2.get())
    u2 = float(u_2.get())
    p2 = float(p_2.get())

    s3 = float(s_3.get())
    l3 = float(l_3.get())
    u3 = float(u_3.get())
    p3 = float(p_3.get())

    e1 = hesapla(l1, p1, u1, s1)
    e2 = hesapla(l2, p2, u2, s2)
    e3 = hesapla(l3, p3, u3, s3)



    canvas.itemconfigure(sonuc1_text, text=f"%e1 = {e1:.3f} {'<' if e1 < 1.5 else '>'} 1.5")
    canvas.itemconfigure(sonuc2_text, text=f"%e2 = {e2:.3f} {'<' if e2 < 1.5 else '>'} 1.5")
    canvas.itemconfigure(sonuc3_text, text=f"%e3 = {e3:.3f} {'<' if e3 < 1.5 else '>'} 1.5")
    toplam_e = e1 + e2 + e3
    if toplam_e > 1.5:
        canvas.itemconfigure(sonuc_text, text=f"%e = {toplam_e:.3f} > 1.5 → Kullanılan Kesit Uygun Değildir")
    else:
        canvas.itemconfigure(sonuc_text, text=f"%e = {toplam_e:.3f} < 1.5 → Kullanılan Kesit Uygundur")
    #uygunluk_durumu = "Uygun" if toplam_e < 1.5 else "Uygun Değil"
    #sonuc_text.set(f"%e = {toplam_e:.3f} < 1.5 → Kullanılan kesit {uygunluk_durumu}")
    #canvas.itemconfigure(sonuc_text, text=f"%e = {toplam_e:.3f} < 1.5 → Kullanılan Kesit {uygunluk_durumu}")
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x500")
window.title("Gerilim Düşümü Hesaplama")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    350.0,
    250.0,
    image=image_image_1
)

#creating button which supports png transparency
quitImage = ImageTk.PhotoImage(Image.open("assets/frame0/button_1.png")) #assets\frame0
quitButton = canvas.create_image(610, 144, image=quitImage)
#canvas.tag_bind(quitButton, "<Button-1>")
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,

    command=sonuclari_kontrol_et,
    relief="flat"
)
button_1.place(
    x=570.0,
    y=127.0,
    width=80.0,
    height=30.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    144.5,
    76.0,
    image=entry_image_1
)
s_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
s_1.place(
    x=132.0,
    y=67.0,
    width=25.0,
    height=16.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    292.5,
    76.0,
    image=entry_image_2
)
s_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
s_2.place(
    x=280.0,
    y=67.0,
    width=25.0,
    height=16.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    447.5,
    76.0,
    image=entry_image_3
)
s_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
s_3.place(
    x=435.0,
    y=67.0,
    width=25.0,
    height=16.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    144.5,
    98.0,
    image=entry_image_4
)
l_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
l_1.place(
    x=132.0,
    y=89.0,
    width=25.0,
    height=16.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    292.5,
    98.0,
    image=entry_image_5
)
l_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
l_2.place(
    x=280.0,
    y=89.0,
    width=25.0,
    height=16.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    447.5,
    98.0,
    image=entry_image_6
)
l_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
l_3.place(
    x=435.0,
    y=89.0,
    width=25.0,
    height=16.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    144.5,
    127.0,
    image=entry_image_7
)
u_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
u_1.place(
    x=132.0,
    y=118.0,
    width=25.0,
    height=16.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    219.5,
    169.0,
    image=entry_image_8
)
p_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
p_1.place(
    x=202.0,
    y=160.0,
    width=35.0,
    height=16.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    372.5,
    169.0,
    image=entry_image_9
)
p_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
p_2.place(
    x=355.0,
    y=160.0,
    width=35.0,
    height=16.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    512.5,
    205.0,
    image=entry_image_10
)
p_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
p_3.place(
    x=495.0,
    y=196.0,
    width=35.0,
    height=16.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    292.5,
    127.0,
    image=entry_image_11
)
u_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
u_2.place(
    x=280.0,
    y=118.0,
    width=25.0,
    height=16.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    447.5,
    128.0,
    image=entry_image_12
)
def open_instagram_profile(event):
    url = "https://www.instagram.com/elektromaker_/"
    webbrowser.open_new_tab(url)
entry_image_13 = PhotoImage(
    file=relative_to_assets("instagram.png"))

entry_bg_13 = canvas.create_image(60, 0, image=entry_image_13)

# Görsele tıklanıldığında fonksiyonu çağırın
canvas.tag_bind(entry_bg_13, '<Button-1>', open_instagram_profile)
u_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
u_3.place(
    x=435.0,
    y=119.0,
    width=25.0,
    height=16.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    248.0,
    265.0,
    image=image_image_2
)

sonuc1_text = canvas.create_text(
    21.0,
    253.0,
    anchor="nw",
    text="%e1=",
    fill="#000000",
    font=("Karla Regular", 16 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    248.0,
    299.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    248.0,
    333.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    248.0,
    367.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    66.0,
    232.0,
    image=image_image_6
)

canvas.create_text(
    43.0,
    223.0,
    anchor="nw",
    text="Sonuç",
    fill="#000000",
    font=("Karla Regular", 16 * -1)
)

sonuc2_text=canvas.create_text(
    21.0,
    289.0,
    anchor="nw",
    text="%e2=",
    fill="#000000",
    font=("Karla Regular", 16 * -1)
)

sonuc3_text=canvas.create_text(
    20.0,
    323.0,
    anchor="nw",
    text="%e3=",
    fill="#000000",
    font=("Karla Regular", 16 * -1)
)

sonuc_text=canvas.create_text(
    21.0,
    357.0,
    anchor="nw",
    text="%e=%e1+%e2+%e3",
    fill="#000000",
    font=("Karla Regular", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
